image: 
  file: Dockerfile
ports:
  - port: 3000 
    onOpen: notify
  - port: 5000
    onOpen: notify
github:
  prebuilds:
    branches: true
    addLabel: true
gitConfig:
  bash.showColorHints: "true"
  bash.showUntrackedFiles: "true"
  bash.showUpstream: "auto verbose name git"
  bash.showStashState: "true"
  bash.showDirtyState: "true"
  bash.hidePwdIfIgnored: "true"
vscode:
  extensions:
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - christian-kohler.npm-intellisense
    - ms-azuretools.vscode-docker

