name: "Release Docker Image"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .dockerignore
      - .profile
      - "**/Dockerfile"
      - "**/.dockerignore"
      - "**/.profile"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: "Setup: QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Setup: Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Login: DockerHub"
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Login: GitHub Container Registry"
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build + Push Docker Image"
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            nberlette/gitpod-enhanced:latest
            ghcr.io/nberlette/gitpod-enhanced:latest
